apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tms-backend
  namespace: tms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tms-backend
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tms-dotnet-reports
  namespace: tms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tms-dotnet-reports
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
